### ISSUE TITLE
About the Iou?

### ISSUE THREAD

**Issue by Yeah-Kun** [Jack-CV/PCN-FaceDetection#40]
Is the Iou about the ground true and predicted box?

**Comment by Jack-CV** [comment]
正样本iou大于0.7，负样本小于0.3，可以参加论文中的细节

**Comment by Yeah-Kun** [comment]
"Positive samples are those windows with IoU  (w.r.t. a face) over 0.7;"这是论文里面的描述。我当时对 "those windows”有疑惑，所以就来请教了；另外，你在里提到的比例2：2：1是怎么实现控制的？
