### ISSUE TITLE
你好，网络输入大小和论文图片中6中的大小不用样

### ISSUE THREAD

**Issue by bravestpeng** [Jack-CV/PCN-FaceDetection#42]
你好检测效果很好，有个地方没看明白，就是代码中网络图片的输入大小和论文图片中6中的所示的图片大小是不一样的，代码中网络的输入数据大小是变化的。

**Comment by Jack-CV** [comment]
因为第一级是按照全卷积的方式输入的，所以输入大小并不是24。overfeat，cascade cnn，MTCNN都是这样做的
