### ISSUE TITLE
whats picture/video/fddb? how should I compile?

### ISSUE THREAD

**Issue by saxenarohit** [Jack-CV/PCN-FaceDetection#48]
Can you help me whats picture/video/fddb? how should I compile?
Is it the path for fddb.cpp?

**Comment by Jack-CV** [comment]
It means “sh compile.sh picture“， “sh compile.sh video“ or “sh compile.sh fddb“.

**Comment by saxenarohit** [comment]
Thanks worked for me!!
Ubuntu 16.0.4
Opencv 3.4.3
