### ISSUE TITLE
Do you plan to release the training code?

### ISSUE THREAD

**Issue by runningJ** [Jack-CV/PCN-FaceDetection#49]
Dear Jack-CV
This a really good job. Do you plan to release the training code? @Jack-CV

**Comment by Jack-CV** [comment]
We will release the code for training，but later.

**Comment by richipower** [comment]
hello @Jack-CV  are there some news on this topic?

**Comment by EngrNadeemShah** [comment]
Hi @Rock-100 Do you have plans of releasing the training code or if you know has anyone else implemented it already?
