### ISSUE TITLE
Really can run at 29FPS in cpu?

### ISSUE THREAD

**Issue by runningJ** [Jack-CV/PCN-FaceDetection#50]
Hi jack-CV
I run the code picture.cpp at my computer Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz.
![qq 20181129193252](https://user-images.githubusercontent.com/13795865/49219413-24dd4300-f40e-11e8-8fcd-95748be0d67c.png)
Is that ok?  @Jack-CV

**Comment by Jack-CV** [comment]
The caffe we use was compiled with openblas. Besides, we test our code with a VGA resolution video as in cam.cpp.

**Comment by runningJ** [comment]
ok thanks
