### ISSUE TITLE
你好，Compile and run这段程序是运行test还是train？

### ISSUE THREAD

**Issue by Windhelm-H** [Jack-CV/PCN-FaceDetection#52]
最近拜读了您的文章，想跑跑程序看看效果，有些小疑惑，不太懂Compile and run中的这段程序，还有picture/crop/video/fddb是怎么得到的，是需要处理FDDB数据集得到吗  谢谢

**Comment by ckqsars** [comment]
@Windhelm-H picture/crop/video/fddb 是4个选项 4选一的 你是不是没有设置caffe的路径

**Comment by Windhelm-H** [comment]
解决了  感谢！
