### ISSUE TITLE
Compile issues

### ISSUE THREAD

**Issue by DecentMakeover** [Jack-CV/PCN-FaceDetection#54]
Hi, Thanks for sharing your work!

When i run 

sh compile.sh picture/crop/video/fddb

`rm picture/crop/video/fddb
rm: cannot remove 'picture/crop/video/fddb': No such file or directory
compile picture/crop/video/fddb
g++: error: picture/crop/video/fddb.cpp: No such file or directory
done`

Any ideas?
Thanks in advance

**Comment by cfoch** [comment]
It seems that documentation is out-of-date. I had to modify the script files by hand.
Try `sh compile.sh code/fddb`

**Comment by DecentMakeover** [comment]
Cool,Thanks for the help.
